### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by jugendhacker** [Handschriftenarchiv/projekt3.0#106]
Habt ihr schon mal über einen Slack Channels für das HSA nachgedacht?

**Comment by Johann150** [comment]
Bis jetzt funktionierte die Kommunikation auch ohne Slack völlig unproblematisch, da es zum Großteil ja nur 2 Contributer gab. Ich sehe auch im Moment keine Veranlassung, einen Slack-Channel zu erstellen.
