### ISSUE TITLE
Kontaktformular

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#11]
unter `/kontakt.html` das Formular zum Laufen bringen. Benötigt bestimmt PHP...

**Comment by Johann150** [comment]
Ich kümmer mich drum, sobald ich Zeit dafür finde

**Comment by Johann150** [comment]
Man bräuchte erst mal ein richtiges Formular mit einem `<form>` Tag

**Comment by vonMitzscha** [comment]
Das heißt, man kann das Formular aus der Template nicht verwerten? oder nur `<form>` Tags rumsetzten?

**Comment by Johann150** [comment]
Naja, ich habe kein `<form>`-Tag gesehen und nur die Information aus so einem Tag kann man verwerten. Es reicht aber, einfach eins um alle relevanten `<input>`'s drum zu machen.

**Comment by Johann150** [comment]
Habe jetzt hoffentlich alle Fehler gelöst, nachdem erst die Nachrichten nicht mitgesendet wurden.

**Comment by Johann150** [comment]
Das sieht doch gut aus:
```
Subject: Kontaktformular HSA
Local Time: 9. August 2017 5:14 PM
UTC Time: 9. August 2017 15:14
From: johann.galle@protonmail.com
To: handschriftenarchiv@protonmail.com

Hallöle,
das ist ein kleiner Test.
Werden mehrere Zeilen angezeigt?
```

Ja, es werden mehrere Zeilen angezeigt. Damit sollte das Kontakformular funktionieren.
