### ISSUE TITLE
Mediathek von Website entfernen

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#110]
Das Iframe in `Mediathek.php`responsible machen, sodass auch auf Mobilgeräten, das Iframe Normalgroß angezeigt wird. Schwierigkeiten bereitet diese Aufgabe darin, dass Prozentangaben für width und height nicht immer Funktionieren…

**Comment by Johann150** [comment]
Das liegt wahrscheinlich daran, dass es für `height` gar keine Prozentangabe gibt.

**Comment by vonMitzscha** [comment]
Ich bin gerade an der Überlegung dran, dass wir die Mediathek im Rahmen der "Minimalisierung des Archivs" einfach einstampfen. Welches kleine Archiv macht denn bitteschön Filme. Und auch bei unseren lässt der Inhalt und die Regelmäßigkeit ja zu wünschen übrig. Daher würde ich sagen: der Imagefilm auf der Startseite und der Vimeo- sowie der YouTube-Account bleiben erhalten, aber die Mediathek wird aus dem Menü genommen. (Reduziert auch wieder die Fehlerquote...).
Stimmst du mir zu @Johann150

**Comment by vonMitzscha** [comment]
Die Seite mit dem Iframe würde ich an sich ja noch behalten, Wer weiß, was noch kommt, aber den Link nehme ich bei der nächst möglichen Gelegenheit raus.

**Comment by vonMitzscha** [comment]
So, erledigt und damit sind auch alle vorangegangen Dinge erledigt…
