### ISSUE TITLE
Schriften werden nicht geladen

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#111]
Bei mir werden die Schriften der Website nicht richtig geladen. Es wäre super wenn z.B. @Johann150 auch noch einmal das ganze bei sich überprüfen könnte. Sonst muss ich mich einmal auf Fehlersuche begeben.
![bildschirmfoto 2018-06-30 um 15 31 26](https://user-images.githubusercontent.com/29487728/42125626-e1b1bc9c-7c7a-11e8-9b8c-875ce2da4c7b.png)

**Comment by jugendhacker** [comment]
@vonMitzscha also bei mir werden die Schriften in Firefox 61.0 auf Windows 10 richtig dargestellt! Welchen Browser benutzt du denn? Und auf welchem System?

**Comment by Johann150** [comment]
Bei mir auch richtig dargestellt.
vonMitzscha benutzt z.Zt. die MacOS Mojave Preview. Daran liegt's wahrscheinlich.

**Comment by jugendhacker** [comment]
Denke ich auch
