### ISSUE TITLE
Exportfunktion im Katalog

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#112]
Die Exportfunktionen im Katalog scheinen nicht wie erwartet zu funktionieren (RIS und EAD). Bei beiden wird der Fehler ausgegeben, dass die angegebene ID in der Datenbank nicht gefunden wurde.

**Comment by vonMitzscha** [comment]
![unbenannt](https://user-images.githubusercontent.com/29487728/43946732-643e695a-9c86-11e8-8607-3037111b1f69.PNG)

**Comment by vonMitzscha** [comment]
Die selbe Meldung auch bei der Linkadresse http://archiv.handschriften.bplaced.de/de/suche/details/export.php, wenn man das EAD exportieren möchte...

**Comment by Johann150** [comment]
Ach ja, da habe ich mal wieder spaß mit den Weiterleitungen...  
Richtige adresse wäre `.../suche/export.php`

**Comment by vonMitzscha** [comment]
Bekommst du das hin :smile: ?
