### ISSUE TITLE
Link in Katalog sichtbar machen

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#116]
Im Katalog auf der Detailsseite besteht die Möglichkeit durch einen Klick auf den Namen des Komponisten weitere Details zu diese zu erfahren. Praktisch wäre es, dies durch eine gestrichelte Unterstreichung deutlich zu machen. Am besten über `text-decoration` mit CSS…

**Comment by Johann150** [comment]
bereits geschehen in 3ae0e8eb598ddea1ba417e2b54a236552279346c
