### ISSUE TITLE
Mediathek Vimeo Vollbild

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#12]
Ich bei mir in Safari das Problem, dass auf der `/mediathek.html` Seite im Vollbild immer noch das Bild des Sliders und der Seitenüberschrift vor dem Video angezeigt wird. In Firefox gibt es das Problem nicht. Der Fehler ist jetzt nicht so wichtig (Schönheitsfehler). Aber es wäre toll, wenn sich eine Lösung finden würde.
Ist aber nicht dringend.

**Comment by Johann150** [comment]
Wenn ich fragen darf, welches Video meinst du?

**Comment by vonMitzscha** [comment]
In der Mediathek jedes Video, aber nur bei Safari. In Firefox ist alles Normal. Ich weiß nicht, ob sich da was machen lässt.

**Comment by vonMitzscha** [comment]
Ich bin gerade dabei eine neue Mediathek zu basteln, da die alte auch nicht responible war `mediathek-beta.html`
Falls du also eine Idee hast, wie man diesen blöden Bug beheben könnte wäre es gut, wenn du die Datei benutzen würdest…

**Comment by vonMitzscha** [comment]
Vielleicht sollte man bei den Videos keine Embeddes sondern ganz normale Videos benutzen `<video></video>`. Fast jeder Browser hat einen modernen integrierten Webplayer. Der Fehler an sich mit dem Vollbild liegt an `div class="row"`

**Comment by Johann150** [comment]
Das Problem liegt darin, dass auch manche Leute noch Internet Explorer nutzen oder ihren Browser einfach nicht aktualisieren. Die Website _sollte_ aber trotzdem rückwäts-kompatibel zu älteren Browsern sein. Ich würde das deshalb **nicht als Lösung sehen**.

**Comment by vonMitzscha** [comment]
Mediathek ist auf dem Weg. Fehler lag in Style für div-Element
