### ISSUE TITLE
Datenbank Suche

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#16]
Ist es möglich dass man in der Volltextsuche der Datenbank schon während des Eingebens des Suchbegiffes Suchvorschläge bekommen kann (war das nicht mal bei Scholar so?).

**Comment by Johann150** [comment]
Ist Prinzipiell möglich, dabei fällt aber auf, dass man mal darüber nachdenken sollte, **welche Felder wirklich zur Volltextsuche gehören sollen bzw. ob alle Felder der Volltextsuche auch in die Vorschau sollen**.
Wenn wir alles so lassen wie bisher, dann wird die Vorschau ungefähr so aussehen, wenn man einfach nur `e` eingibt: (jeder Vorschlag auf einer Zeile)
```
11x Sopran<br>6x Alt<br>9x Tenor<br>9x Baß
17x Sopran<br>10x Alt<br>35x Tenor**<br>43x Baß**
1x Kanbenchorpartitur
1x Knabenchor
1x Sopran<br>1x Alt<br>1x Tenor<br>1x Baß
1x Tenor II
2x Sopran<br>2x Alt<br>2x Tenor<br>3x Baß
4x Sopran<br>4x Alt<br>4x Tenor<br>4x Bass
5x DIN A5<br>1x DIN A4<br>1x ehemals DIN A4
5x Knabenchor (auch Jugendchor)<br>5x Männerchor (Tenor I,II)
5x Knabenchor (auch Jugendchor)<br>5x Tenor<br>5x Baß
5x Sopran<br>3x Alt<br>4x Tenor<br>4xBass
5x Sopran<br>4x Alt<br>4x Tenor<br>4x Bass
5x Sopran<br>5x Alt<br>5x Tenor<br>5x Baß
5x Sopran<br>5x Alt<br>6x Tenor<br>8x Baß
5x Sopran<br>6x Alt<br>4x Tenor<br>5x Baß
6x Gesamtchor
6x Knabenchor (auch Jugendchor)<br>5x Tenor<br>5x Baß
Abendwolke
Alexander Tichonowitsch Gretschaninow
```

Es mag vielleicht ein schlechtes Beispiel sein, aber es sieh schon verwunderlich aus, mit den ganzen Anzahlen, obwohl ja Ergebnisse wie die letzten beiden mehr Sinn machen würden 😒 ...

**Comment by vonMitzscha** [comment]
Nein, um Himmelswillen :) Am praktischsten wäre es, wenn nur die Felder `Komponist` und `Titel` in der Volltextsuche und in der erweiterten Suche für jedes Feld die Entsprechnde Spalte in der Datenbank (z.B. Erweiterte Suche: Vefasser --> nur die Verfasser werden durchsucht)
