### ISSUE TITLE
Datenbank EAD

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#17]
Für die Übernahme der Datenbank Daten vom HSA zur DDB wäre es nötig, die Datenbank für den Export auf das Standart EAD-Format zu "mappen".
[Hier ist eine Übersicht über EAD](https://www.landesarchiv-bw.de/web/55577)

**Comment by Johann150** [comment]
Ich habe mal ein Beispiel hinzugefügt: 7c20f7aa393fabbb33ac46529ba2093fb6c8d57d
Bitte mal schauen, ob das soweit ok ist.

**Comment by Johann150** [comment]
`export.php` muss nach Rücksprache mit DDB noch geändert werden.
#26 muss noch warten.

**Comment by Johann150** [comment]
@vonMitzscha Es sind bei mir noch ein paar Fragen aufgekommen:
- Sollen die Introitensammlung und der Rest des Archives getrennt werden?
- Wie ist das Verfahren bei mehreren Digitalisten?

**Comment by Johann150** [comment]
Also die Introitensammlung und der Rest werden nicht getrennt und ich nehme an, dass es mit den Digtalisaten so i.O. ist.

**Comment by Johann150** [comment]
Die EAD-Funktionalität muss nach mal für die Normdaten angepasst werden.

**Comment by Johann150** [comment]
Wurde mit #37 abgearbeitet.
