### ISSUE TITLE
Suchvorschläge Safari

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#21]
Möglichkeit auch in Safari mit der "neuen" Suche suchen zu können. input-field ?

**Comment by Johann150** [comment]
Was meinst du mit 

> input-field ?

**Comment by Johann150** [comment]
Also das Problem liegt auf jeden Fall nicht an webkit, in Chrome funktionierts einwandfrei. ☹️

**Comment by Johann150** [comment]
Tritt der Fehler eigentlich auch in der erweiterten Suche auf?

**Comment by Johann150** [comment]
eventuelle Alternative: https://www.w3schools.com/php/php_ajax_livesearch.asp

**Comment by Johann150** [comment]
gelöst mit 56f23e592b5ca2444a254db676b9e05e962d2409
