### ISSUE TITLE
Issuu-Embedded Style

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#27]
Hintergrundfarbe des Automtisch erzeugten Embeddeds in der Datenbank zu `#ffffff`
Das Format, wie es bei 

> Gott der Herr

 ist als Standart nehmen.

**Comment by Johann150** [comment]
Das hat ja nichts mit unserem Programm zu tun, das müsste in Issuu geändert werden. Darauf haben wir keinen Einfluss, denn das ist ja in einem `<iframe>` drin.

**Comment by Johann150** [comment]
Alles was in der Datenbank steht ist ja nur (z.B. für Gott der Herr):
```
//e.issuu.com/embed.html#25938217/39210329
```
und das wird eingesetzt:
``` HTML
<iframe width=100% height=394 src="//e.issuu.com/embed.html#25938217/39210329" frameborder="0" allowfullscreen>
...
```

**Comment by vonMitzscha** [comment]
Dann hat sich die Sache erledigt…
