### ISSUE TITLE
Export-Knopf

### ISSUE THREAD

**Issue by Johann150** [Handschriftenarchiv/projekt3.0#28]
Es sollte für die Noten in `suche/details.php` einen Link bzw. Button geben, um die Daten in den jeweiligen Formaten zu exportieren.

**Comment by vonMitzscha** [comment]
Wollen wir uns an den Export-Formaten der SLUB orientieren?

**Comment by Johann150** [comment]
Ja, daran dachte ich.

**Comment by vonMitzscha** [comment]
Findet sich da vielleicht gleich was bei der SLUB? [SLUB](https://github.com/slub)

**Comment by vonMitzscha** [comment]
Ich habe jetzt schon alles auf die Domain hochgeladen, da du es gemerged hast. Aber es fehlt noch der Button. Ich würde vorerst sagen, dass wir einfach einen Button (vom Style her, wie in der `kontakt.php` nehmen und immer ganz am ende der `/suche/details.php` hinsetzten. Also noch unter die CC-Lizenz.

**Comment by vonMitzscha** [comment]
Dann könne später auch noch andere Buttons für eventuelle andere Formate hinzugefügt werden.
![desktop hdscreeen](https://user-images.githubusercontent.com/29487728/30290774-eca0aaee-9730-11e7-938d-11741e2d9cbe.png)

**Comment by Johann150** [comment]
welche `class` braucht der Button?

**Comment by vonMitzscha** [comment]
```
<div class="col-md-12">
 <div class="form-group">
   <input type="submit" value="Nachricht senden" class="btn btn-primary">
 </div>
</div>
```
