### ISSUE TITLE
htaccess Entwurf

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#30]
`htaccess`überarbeiten als finalen Entwurf für die Veröffentlichung im Herbst

**Comment by Johann150** [comment]
Was soll den daran noch geändert werden?

**Comment by vonMitzscha** [comment]
Es wäre Praktisch, wenn man mache Bilder (z.B. im Verzeichnis `images/blog/`) öfters neu läd als im  Verzeichnis `images/kontakt`

**Comment by Johann150** [comment]
Warum sollten die Bilder neu geladen werden? Neue Bilder werden ja unter einem neuen Namen angelegt und die müssen ja dann sowieso geladen werden. Und vergangene Blog-Einträge werden doch nicht noch mal bearbeitet, oder?

**Comment by vonMitzscha** [comment]
Aber die Bilder werden in Unterverzeichnissen angelegt. Sagt man also `/images/` soll alle 3 Jahre neu geladen werden wird er neue Blogeintrag unter `images/blog/blogbeitrag1/` nicht neu geladen.

**Comment by Johann150** [comment]
NEIN, der Browser bekommt den Header, die Datei _nicht_ neu zu laden nur mit einer Datei zusammen.
Und wie gesagt: Neue Dateien müssen ja sowieso geladen werden. Denn wenn da steht
```HTML
<img src="images/blog/blogbeitrag1/header.jpg"/>
```
dann kennt der Browser die Datei ja noch nicht und läd sie erst mal herunter und erhält **dann erst** die Nachricht: "Das kannst du jetzt für 3 Jahre so behalten."

Also nochmal zusammengefasst: **Neue Dateien werden immer erst mal heruntergeladen.** (_Woher sollte der Browser die sonst auch nehmen? Sich neu ausdenken?_)

**Comment by vonMitzscha** [comment]
Ok verstanden.
