### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#32]
Wollen wir eigendlich für unsere größeren Fortschritte die Release-Funktion von GitHub nutzen. Also Version v.1.3.2 ?

**Comment by Johann150** [comment]
Ich dachte, wir veröffentlichen erst im Herbst? Bis da hin brauchen wir keine Releases.
Und auch sonst brauchen wir die eigentlich nicht bzw. ich wüsste nicht wozu. Wer interessiert sich denn für die alten Verionen der Website?

**Comment by vonMitzscha** [comment]
Ok, dann releasen wir erst, wenn alles der "Öffentlichkeit" zugänglich gemacht wird.
