### ISSUE TITLE
Suche Hover

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#33]
Div-Element in der `suche/index.html` Datei soll im Falle und der Dauer eines Hovers, dass "Verschwommene" Hintergrundbild der Seite in ein klar aufgelöstes Bild umfaden. Zusätzlich soll ein Text erscheinen, in der der Name des Digitalisats (manuell im Code Eingeben) und der Link zur Resourcce erscheint.

**Comment by vonMitzscha** [comment]
erste Ansätze im Branch `suche-hover`

**Comment by Johann150** [comment]
in `search/index.html` gibt es sehr viele `<div>`-Elemente. Welches meinst du? (ID, ...)

**Comment by vonMitzscha** [comment]
[ungefähre Zielsetzung mit Figma](https://www.figma.com/proto/GTNiwrTAvpu4c8E8SHncBjD3/HSA-Suche?node-id=1%3A2&scaling=contain)

**Comment by Johann150** [comment]
also ein neues `<div>`-Element, dass dazu dient, Auskunft zum Hintergrundbild zu geben, richtig?

**Comment by vonMitzscha** [comment]
Ja. Aber alles schon so gut wie abgeschlossen. Es muss nur noch was mit der Eingangsanimation und der Dauer der Anzeige gemacht werden.

**Comment by Johann150** [comment]
Also jetzt ist es schon fertig ( #36 ).
