### ISSUE TITLE
Übersetzung (generell)

### ISSUE THREAD

**Issue by Johann150** [Handschriftenarchiv/projekt3.0#4]
Zur Zeit ist die Website nur auf Deutsch einsehbar, allerdings wäre eine Englische Version vielleicht gut.
Allerdings ist die Frage, ob es einfach nur einen Ordner für jede Sprache geben soll also z.B. einen Ordner `/en`, welcher die übersetzten Seiten enthält, oder ob die Website mithilfe von PHP übersetzt werden soll.
@vonMitzscha, welche Variante ist besser?

**Comment by vonMitzscha** [comment]
Es gibt in der index.html schon ein Kommentar, wo ein zweites "Menü" Icon eingefügt werden kann und dann auch schon ein Schwarzer Menü-Layer mit Deutsch und English auftaucht. Muss nur noch was in der Style.css geändert werden, damit man das auch Sieht. Und das Menü-Icon sollte auch zu einem "Sprach-Icon" geändert werden.
Ich würde die Variante mit dem neuen Ordner preferieren, um dann dort alles reinzukopieren...

**Comment by vonMitzscha** [comment]
Allerdings sollte man die Englisch-Übersetzung hinten anstellen, da sich das Projekt 3.0 ja vorrangig um die "Zurückbesinnung" auf das Wesentliche des Archives konzentriert und nicht ein Business-Projekt propagieren soll...

**Comment by Johann150** [comment]
Ja, wahrscheinlich ist es auch einfacher, als wenn man in irgendwelchen Wörterbüchern immer alles reinschreiben muss, um es mit PHP zu übersetzen. Ich hatte allerdings schon an die Übersetzung gedacht, weil mir im Moment nicht einfiel, was an Projekt3.0 noch zu tun wäre.

**Comment by vonMitzscha** [comment]
Wenn dir nichts einfällt. Wir müssten noch die Datenbank füllen. Es warten noch 200 Handschriften, Drucke und Kopien auf uns. Und ab kommenden Monat können wir dann auch weiter digitalisieren.

**Comment by vonMitzscha** [comment]
Genrelle Frage: du hattest doch mal so ein Tool, um Websites zu Übersetzen (vgl. Scholar). Könnte man dies auch bei Projekt 3.0 anwenden?

**Comment by Johann150** [comment]
Jaaa.... (<https://github.com/Johann150/multilang>).
Die Frage ist, ob wir das anwenden wollen, denn es würde z.B. erfordern, dass wir alle Datein in der Datenbank normieren (z.B. statt Deutsch immer de...). Darüber sollten wir aber vielleicht angesichts #17 sowieso nachdenken...

**Comment by vonMitzscha** [comment]
Nur ganz theoretische Gedankengänge: Wenn ich ins Englische übersetzten wöllte, dann auch nur den Content der Website nicht der Archivdatenbank (wenn möglich). Aber das ganze soll, wenn es kommen soll, erst nach der Veröffentlichung bzw. nach der Fertigstellung der Datenbank kommen.

**Comment by Johann150** [comment]
Wir sollten aber trotzdem über eine Normierung der Daten nachdenken.

**Comment by jugendhacker** [comment]
Könnte man das nicht so ähnlich lösen wie unter Android? Man hat dort einfach mehrere XML Dateien wo Strings drinn stehen und dann gibts halt welche für Deutsch, Enlisch usw.  und man kann dann einfach an der Stelle den String aus der passenden Datei nehmen!

**Comment by Johann150** [comment]
Mein "Plugin" [multilang](https://github.com/Johann150/multilang) funktioniert so ähnlich. Schau doch einfach mal dort für weitere Informationen vorbei. Das Projekt ist übrigens erst für nach der Veröffentlichung (siehe #42) geplant, da es nicht so wichtig für die Funktionalität der Website ist.

**Comment by jugendhacker** [comment]
OK dann ist ja gut

**Comment by Johann150** [comment]
Ich denke, dass wir nicht alles mit  [multilang](https://github.com/Johann150/multilang) machen sollten. Z.B. der Blog sollte nicht damit übersetzt werden, das wäre zu umständlich.
Aber Seiten, auf denen eher einzelne Worte statt Sätzen vorkommen, wie die `/suche`-Seiten sind dafür prädestiniert.

**Comment by jugendhacker** [comment]
Ich arbeite gerade für euch an einer Übersetzung mit multilang, evtl. schreibe ich auch noch ein kleines Tool was das generieren der nötigen Dateien vereinfacht ;-)

**Comment by vonMitzscha** [comment]
OK. Visuell ist es der Plan das selbe Element wie für das Menü zu nehmen (nur ein ein anderes Icon aus Icomoon) und dann im "Menü" die Sprachen Aufzulisten…

**Comment by vonMitzscha** [comment]
Prioritäten liegen dabei auf:
- einer Englischen Übersetzung
- der `index.php`, `archiv.php`, `impressum.php`

Blog, Mediathek, Verwaltung und Datenbank können ersteinmal vernachlässigt werden. Wenn du jedoch ein allgemeines Tool schreibst, kannst du die ja gleich mit einbeziehen.

**Comment by Johann150** [comment]
Das Design/Menü an sich ist ja erst mal nicht so wichtig, das kann man ja später noch machen.

**Comment by Johann150** [comment]
Dazu muss die Übersetzung ja erst einmal funktionieren, sonst lohnt es sich ja nicht.

**Comment by jugendhacker** [comment]
Ich sehe das genau so und somit kümmere ich mich erstmal ums eigentliche übersetzen und eigentlich sollte multilang auch die vom Browser übermittelte Sprache gleich automatisch auswählen sofern verfügbar! Aber ich glaube da muss ich Mal noch nen Paar fixes machen.

**Comment by Johann150** [comment]
Mit #75 sind wir doch jetzt schon mal einen Schritt voran gekommen.

**Comment by Johann150** [comment]
Sollte vielleicht `.htaccess` noch mal geändert werden? Man könnte ja z.B. `/de/blog` so umleiten, dass man in jedem Fall die *de*utsche Übersetzung bekommt. Und dann `/en/blog` usw. entsprechend.

**Comment by Johann150** [comment]
Ich habe die Notizen im zugehörigen [Projekt](https://github.com/Handschriftenarchiv/projekt3.0/projects/1) jetzt so geändert, dass die Schritte zur Übersetzung klar sein sollten.

**Comment by vonMitzscha** [comment]
@Johann150 könnte man nicht einen extra Branch für die ganzen Übersetzungen und alles was dazu gehört machen. Es ist echt kompliziert, wenn man Daten auf die "echte" Domain hochladen will

**Comment by Johann150** [comment]
Was ist daran kompliziert?
So wie es jetzt ist, enthält der `master`-Branch die produktive Version der Webseite.

**Comment by jugendhacker** [comment]
@Johann150 hast du die aktuelle Verion von multilang hier schon integriert?

**Comment by jugendhacker** [comment]
@Johann150 hast du die aktuelle Verion von multilang hier schon integriert?

**Comment by Johann150** [comment]
Ja, auch das Translator Tool ist schon eingebaut.

**Comment by Johann150** [comment]
Wie würde man die Vorschauen der Blog-Einträge in `blog/index.php` am besten übersetzen? Sollte man die eher mit `__()` oder mit `__chunk()` übersetzen?

**Comment by jugendhacker** [comment]
Ich würde es mit `__chunk()` machen

**Comment by Johann150** [comment]
Ich denke auch, dass es so besser ist.

**Comment by vonMitzscha** [comment]
Ich denke mit dem am Jahresende 2018 beschlossen Ende der Arbeit am HSA können wir getrost auch die Übersetzung der wichtigsten Seiten als beendet ansehen…
