### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by Johann150** [Handschriftenarchiv/projekt3.0#40]
Einfaches kleines Script, um zu sehen, welche Seiten am beliebtesten sind.
Dazu kann vielleicht eine Umleitung über `.htaccess` erfolgen...

Dies sollte möglichst wenige Nutzer-Daten sammeln, also keine IP's sondern nur Zugriffe und evtl. das Herkunftsland.

**Comment by Johann150** [comment]
Was soll alles gespeichert werden?
- [x] auf welche Seite wurde zugegriffen
- [x] wann wurde zugegriffen?
- [x] von wo wurde zugegriffen?
- [ ] unique views?
- [ ] mobiles Endgerät?

**Comment by Johann150** [comment]
@vonMitzscha Was ist der Plan?

**Comment by vonMitzscha** [comment]
Welcher Plan? Einfache Analtyics, die bestenfalls über eine einfach Passwort gesicherte Seite zugänglich sind (auf die UI ist da nicht so zu achten…)

**Comment by Johann150** [comment]
Unique Views bedeuten aber, dass wir bei den Nutzern ein Cookie speichern müssen. D.h. wir brauchen etwas à la "Ich bin mit der Nutzung von Cookies verantwortlich."

**Comment by Johann150** [comment]
Wir können das Ganze ja auch öffentlich zugänglich machen, dann muss man halt mit dem hässlichen Design leben. Halt ohne verlinkung, sodass man nicht drauf kommt.

**Comment by vonMitzscha** [comment]
Ok, aber, um alles von heute Besprochene noch einmal festzuhalten: Ohne Cookies und alles in das Verzeichniss `/verwaltung/`

**Comment by Johann150** [comment]
D.h. auch keine unique views sondern einfach nur views.

**Comment by vonMitzscha** [comment]
Genau

**Comment by Johann150** [comment]
Für die Diagramme, die am Ende produziert werden sollen , werde ich Highcharts verwenden. Dann wird das Rendern in den Browser verschoben und der Server hat weniger Last.

**Comment by Johann150** [comment]
Es sähe dann in etwa so aus: (Dort wo der Hinweis ist, war mein Mauszeiger gerade)
![grafik](https://user-images.githubusercontent.com/20990607/30515348-125b0416-9b26-11e7-8c0e-2143d8d785e2.png)

@vonMitzscha Ist das Design soweit i.O.?

**Comment by vonMitzscha** [comment]
Das Design ist Wunderhübsch!

**Comment by Johann150** [comment]
✔️ ( #48 )
weiteres Verfahren siehe #49
