### ISSUE TITLE
Verfahren mit der alten Website

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#41]
1. neue `index.html` für `notenarchiv-dkc.bplaced.de` auf der das Veröffentlichungsdatum des Projektes 3.0 und der Trailer hierfür zu sehen sind.
2. die alte Website darf jedoch nicht gelöscht werden (nicht komplett) weil sich hier noch die nicht übernommenen Daten der Archivalien in Digitalerform befinden. Man müsste also über eine Verlegung des noch wichtigen Materials auf eine Andere Domain oder ein anderes Verzeichniss nachdenken (z.B. `old.handschriften.bplaced.de` : hier befinden sich alle "wichtigen Wordpress-Überreste, sodass das Projekt 3.0 schon Problemlos released werden kann)

**Comment by Johann150** [comment]
Das Projekt 3.0 kann ja unabhäng von der Existenz der alten Website veröffentlicht werden. Ich würde da sogar ein bis zwei Wochen überlappen zwischen Existenz der beiden Webseiten. In diesen zwei Wochen wäre dann die finale Zeit, um die restlichen Daten zu übernehmen. Und nach diesen zwei Wochen wird dann eine neue `index.html`, wie schon gesagt, auf der alten Webseite. Dann nach ein paar Monaten die alte Webseite komplett löschen.

Auf jeden Fall darf es keine Lücke zwischen Existenz der beiden Webseiten geben.

**Comment by vonMitzscha** [comment]
Alle 404 (von denen es bald einen Menge geben wird) der Seite `notenarchiv-dkc.bplaced.com` sowie die `index.php` werden auf `hsa.bplaced.com` umgeleitet. Nicht vergessen, am 20.10. die Weiterleitung bei `notenarchiv-dkc.bplaced.com` und `hsa.bplaced.com` auf `archiv.handschriften.bplaced.de` umzuleiten.

**Comment by vonMitzscha** [comment]
Alle Wordpress Seiten, Plugins, Media, etc. werden jetzt gelöscht. Bis auf die `suche` und den `blog`. Alle 404 werden damit auf die `hsa.bplaced.de` umgeleitet.

**Comment by vonMitzscha** [comment]
Es gab ein Problem: wegen diverser Wordpress-Datein wurde der gesamte Traffic der alten Domain auf `hsa.bplaced.de` umgeleitet. Es gab also auch kein rankommen an die Datenbank bzw. Wordpress-Post mehr. Darum folgende **End**-Lösung: Alle Archiveinträge wurden von der WP-Site als PDF (eine Datei) exportiert. Diese gilt jetzt als Grundlage für die Datenübernahme. Die Domain `notenarchiv-dkc.bplaced.com` wurde jetzt insofern aufgegeben, dass Sie jetzt **immer** auf die Introduction-Page für das Projekt 3.0 umleitet. Die Daten liegen vorsichtzalber noch auf der Domain, aber um an diese über den Browser ranzukommen, muss die `index.php` wieder in das Anfangsstadium (also ohne Umleitungen) zurückgesetzt werden.

**Comment by Johann150** [comment]
Es sollte aber noch irgendeine Notitz geben, dass die Website gerade in der Entwicklung ist und demächst eine neue Webseite **unter der neuen Domain** kommt.

**Comment by vonMitzscha** [comment]
Ab dem 20.10 erscheint auf der Umleitungswebsite die Nachricht, dass die Domain `notenarchiv-dkc.bplaced.com` nicht länger existiert. Die Umleitung ist deshalb eingerichtet, damit der User nicht in seiner Routine bleibt und immer wieder zu Notenarchiv-dkc.bplaced.com geht sondern sich merkt das das ganze auch über hsa.bplaced.de laufen kann. (Ist sowieso kürzer).
Und zweitens ging es mit den vorhandenn wordpress-Dateien, die ich noch nicht Löschen wollte nicht so einfach, da die Umleitungs-HTML-Datei aus mehren Dateien und Ordner besteht (ich habe das ganze mit Muse CC erstellt, da ich zu faul war und schnell ein Responsible-Seite brauchte)

**Comment by Johann150** [comment]
Das Problem ist: Es merkt doch keiner, dass er umgeleitet wurde! Du musst immer vom dümmsten Fall ausgehen, in dem halt nicht in die Adresszeile geschaut wird.

**Comment by vonMitzscha** [comment]
Jedenfalls funtkioniert alles und die Datenbank, die die einzig wichige Rolle auf der Alten Website gespiel hat, ist als PDF exportiert und kann somit weiter übernommen werden.
Generell sehe ich das Problem mit den Weiterleitungen gar nicht so schlimm, weil wie groß ist der Traffic unserer Website…?
