### ISSUE TITLE
Neue Seite

### ISSUE THREAD

**Issue by jugendhacker** [Handschriftenarchiv/projekt3.0#43]
Hi ich verfolge euch jetzt schon einige Zeit und nun zwei Fragen zu dieser [Seite](http://hsa.bplaced.de/):

- Warum ist der Text ein Bild?
- Warum könnt ihr nicht euren Twitter Account irgendwie Verlinken?

**Comment by Johann150** [comment]
Das liegt daran, dass @vonMitzscha die Übergangs-Website mit Adobe Muse gestaltet hat. Das wandelt alle Seitenelemente in SVGs um, da somit einfach ein responsibles Design erreicht wird.

**Comment by jugendhacker** [comment]
Aber die Benutzerfreundlichkeit wird dadurch nicht wirklich besser! Man kann ja nicht einfach z.B. euren Twitter Namen aus nem Bild kopieren!

**Comment by vonMitzscha** [comment]
Es handelt sich jedoch nur um eine **Übergangswebsite**, die den Zweck erfüllt, über die aktuellen Vorgänge der Website des Handschriftenarchiv zu Informieren. Die Funktion spielt dabei, solide gesagt, gar keine Rolle!
