### ISSUE TITLE
DFG-Viewer

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#44]
Hier eine anerkannte Alternative zu `issuu.com` für Digitalisate: Der DFG-Viewer.
@Johann150 wäre es möglich so etwas auch in unserer `/suche/details.php` zu integrieren?
[Hier weitere Informationen](http://dfg-viewer.de/ueber-das-projekt/was-ist-der-dfg-viewer/)

**Comment by vonMitzscha** [comment]
Ich glaube die verscheidenen Dateiformate, die wir für die Digitalisierung benötigen würden, werden die Idee schon zum Scheitern bringen: [Metadaten](http://dfg-viewer.de/profil-der-metadaten/)

**Comment by vonMitzscha** [comment]
Hier ein Link betreffs der Implemetierung […](http://dfg-viewer.de/ueber-das-projekt/implementierung/)

**Comment by vonMitzscha** [comment]
Ich habe den DFG-Viewer der SLUB mal in unseren Account geforked.

**Comment by vonMitzscha** [comment]
Dieses [hier](https://github.com/kitodo/kitodo-presentation) könnte uns vielleicht mit den Metadaten und Dateiformaten helfen.

**Comment by Johann150** [comment]
Aber das bedeutet doch schon wieder ein neues Export-Format (METS), oder? 😒 
Wofür ist dieses jetzt wieder gut?

**Comment by Johann150** [comment]
Und wofür hast du geforked? Wir können doch auch den Service der SLUB nutzen...

**Comment by vonMitzscha** [comment]
Geforked habe ich, wenn wir es nutzen wollen, beötigen wir auch die Ausführenden Dateien und können gegebenenfalls Anpassungeb vornehmen. Und ja, bei METS und Co handelt es sich leider 😒 um neue Exportformate. Wieder in XML und es scheint so, dass die Bilder, die angezeigt werden sollen über dieses Verknüpft und mit relevanten bibliographischen Daten verbunden werden. Ich bin noch auf der Suche, ob man solche Dateien auch generieren kann, weil die großen Bibliotheken werden ja auch nicht für jedes Digitalisat eine eigene Datei "handmade" schreiben.

**Comment by vonMitzscha** [comment]
Vielleicht hilft uns auch [das hier](http://www.kitodo.org/) weiter?
Aber ich glaube das könnte uns weiterhelfen: Eine [Webbrowser basierte Software zum Erstellen und Veröffentlichen von Digitalisaten](http://www.kitodo.org/software/kitodoproduction/). Und der DFG-Viewer wird ja hauptsächlich von der SLUB entwickelt. Ich werde in diese Richtung mal weiter recherchieren…

**Comment by vonMitzscha** [comment]
Intern abgesprochen
