### ISSUE TITLE
Vimeo-Embeddes Responsible machen…

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#47]
Keine Javaplayer und auch kein Vimeo-Embedded in der `mediathek.html` sondern `<video>`-Tags. Erste Umstrukturierung in der `mediathek-beta.hmtl`

**Comment by Johann150** [comment]
Nur eine Frage: Warum soll das geändert werden?

**Comment by vonMitzscha** [comment]
Da beispielsweise bei Proxy-Servern (vgl. Alu) Iframes nicht angezeigt werden. Über den Tag `<video>` kann man somit auf eigene Videos zurückgreifen, unabhängig von den Tools anderer Unternehmen

**Comment by Johann150** [comment]
Und die Videos kommen Fan von wo? Sie müssten dann ja als Video-Dateien gespeichert werden und **nicht als Vimeo**.

**Comment by vonMitzscha** [comment]
Die Videos werde dann im Verzeichnis `/videos` liegen....

**Comment by Johann150** [comment]
Und der Server wird ganz schnell voll...
Das hatten wir doch schon mal.

**Comment by Johann150** [comment]
Und außerdem stellt das für mich keinen Grund dar, von Vimeo wegzugehen.

**Comment by vonMitzscha** [comment]
Viemo bleibt ja auch, nur beitet der externe verschiedene Nachteile wenn es um Mobile Endgeräte geht. So bildet sich bei kleineren Screens ein anderes Format und ein ein hässlicher schwarzer Rahmen entsteht. Was bei dem Browser internen Player kein Problem ist (zumindest bei Safari und Mozilla Firefox)

**Comment by vonMitzscha** [comment]
![bildschirmfoto 2017-09-18 um 21 15 22](https://user-images.githubusercontent.com/29487728/30559968-abd809d6-9cb6-11e7-9e0a-8948418dbb83.png)

**Comment by vonMitzscha** [comment]
Sehe keine Lösungsmöglichkeit, den Vimeo-Player responsible zu machen, ohne das ein schwarzer Rand entsteht…

**Comment by Johann150** [comment]
vielleicht mit <http://embedresponsively.com/>?

**Comment by vonMitzscha** [comment]
Danke, die Rettung…
Bastel noch alles um…

**Comment by vonMitzscha** [comment]
erstmal egal, machen wie später. Es funktioniert ja alles soweit…
