### ISSUE TITLE
Analytics Umrüstung

### ISSUE THREAD

**Issue by Johann150** [Handschriftenarchiv/projekt3.0#49]
Es müssen alle Seiten zu `.php` geändert werden und es muss die erste PHP-Zeile
```PHP
require_once "analytics.php";
```
sein. (In Unterverzeichnissen ist evtl. der Pfad mit `..\analytics.php`  anzugeben)

Für alle Dateien, danach keine PHP-Dateien sind (z.B. `.pdf`) werden entweder keine Statistiken angefertigt oder es wird eine alternative Lösung benötigt.

**Comment by Johann150** [comment]
Vielleicht kann @vonMitzscha die Änderung der HTML-Dateien machen (bitte in einem Extra-Branch)?

**Comment by vonMitzscha** [comment]
Alle Links in auf allen Seiten müssen noch von `.html` zu `.php`geändert werden…

**Comment by Johann150** [comment]
Ferdsch

**Comment by vonMitzscha** [comment]
Wir haben ein Problem!
![bildschirmfoto 2017-09-18 um 22 17 27](https://user-images.githubusercontent.com/29487728/30562586-40f4a436-9cbf-11e7-9353-c79a8f335496.png)

**Comment by vonMitzscha** [comment]
Wir haben ein Problem
![bildschirmfoto 2017-09-18 um 22 17 27](https://user-images.githubusercontent.com/29487728/30562599-4c337a0c-9cbf-11e7-9eb0-236e36b9885a.png)

**Comment by vonMitzscha** [comment]
Was ist mit der Website passiert !?

**Comment by Johann150** [comment]
Beruhige dich doch mal! Das liegt daran, dass die Analytics überall eingebunden sind, aber auf bplaced keine Verbindungen möglich sind. Deshalb kann nicht das Land herausgefunden werden.
Dieses Feature muss also leider entfernt werden.

**Comment by vonMitzscha** [comment]
Ist schon gut. So lange das bis Morgen (Termin Grüner) wieder funtkioniert iat ja alles OK…

**Comment by vonMitzscha** [comment]
Es funktioniert wieder alles. @Johann150 Retter in der Not 😄.
