### ISSUE TITLE
Issuu Style

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#5]
Der Style der Embededs, bzw. der PHP-link müssten einem angemessenen Seitenverhältnis angepasst werden.
@Johann150 Gibt es eine einfache Lösung?
![bildschirmfoto 2017-07-13 um 10 38 29](https://user-images.githubusercontent.com/29487728/28158018-a5a78146-67b8-11e7-841f-c43e35557cd6.png)

**Comment by Johann150** [comment]
Ich kann dir leider nicht ganz folgen, bei mir sieht das ganze wie folgt aus:

![grafik](https://user-images.githubusercontent.com/20990607/28170767-a56e98d0-67e6-11e7-820e-9468743c2ec3.png)

eventuell ältere Browserversion, irgenwelche Fehler in der Browser-Konsole?

**Comment by Johann150** [comment]
@vonMitzscha Bitte mal die neue Version testen
(b901ec348b5e254f2f9d7d7ced6eb98baf60380a)

**Comment by vonMitzscha** [comment]
Jetzt funktioniert alles. Aber ich habe noch eine kleine Style Frage: Wäre es möglich die Digitalisate entweder durch ein `<hr>` abzutrennen oder wenigstens wieder mit rechtzeitig und linksseitig zu sortieren, da es komisch aussieht, wenn alles links- und rechtsseitig ist und die Digitalisate in der Mitte. 
Und beim Maulbeerbaum, auch generell alle Musescore Dateien würde ich zum Typus Audio oder besser noch zu der neuen Kategorie Rekonstruktion setzten, da es ja keine "bildliche" Digitalisierung ist. Alternativ könnte man die Musescore Datei auch zu mp3 exportieren und als Audiodatei in den Audioplayer setzten. Aber so sieht das blöd aus: Issuu zu issuu und musescore zu musescore. Und in der Tabellenform wie bisher...

**Comment by vonMitzscha** [comment]
Mit dem Strich in der Mitte des vorgegangenen Kommentares meinte ich `<hr>`

**Comment by vonMitzscha** [comment]
Hat das noch was zu bedeuten? @Johann150 
![bildschirmfoto 2017-07-13 um 17 51 08](https://user-images.githubusercontent.com/29487728/28175217-e5b9ab7a-67f3-11e7-80bc-0f99ba053676.png)

**Comment by Johann150** [comment]
Also das abtrennen mit `<hr>` ist kein Problem, aber ich glaube es ist besser wenn es einfach mit in die Tabelle kommt.
Die Musescore-Daten zu audio zu schieben ist allerdings nicht möglich, denn da wird kein iframe erzeugt, sondern nur ein Audio-Player. Und die Musescore-Daten zu mp3 zu exportieren ergibt keinen Sinn, denn dann fehlt ja der ganze Effekt der Erfassung der Noten. Der Ton ist bei Musescore eher ein angenehmer Nebeneffekt.
Die Erstellung einer neuen Kategorie würde allerdings eine Änderung an der Datenbank erfordern und streng genommen ist Musescore ja auch eine Digitalisierung, und noch dazu ist sie sehr bildlich, denn es sind ja die Noten zu sehen.

**Comment by vonMitzscha** [comment]
Ich würde Musescore ersteinmal komplett weglassen. Zumal nur "1,5" Werke digitalisiert wurden. Issuu reicht ersteinmal. Für Musescore Dateien schreibe ich immer einen extra Blogeintrag. So werden erstens diese "vortschrittlich" Digitalisierten Werke hervorgehoben und zweitens: Wie viele Musescore Dateien für das HSA erstellt die Abteilung Digitale Datenübernahme JÄHRLICH?

**Comment by vonMitzscha** [comment]
Wir sollten uns vor allen Dingen auf die Digitalisierung und Publizierung via Issuu fokusieren.

**Comment by vonMitzscha** [comment]
Zu den Issuu Embdedes. Funtkioniert das schon, dass alles in eine Tabelle zu stellen? Dann kannst du ja eine neue Pull Request starten. Ich "merge" gerne...

**Comment by Johann150** [comment]
du kannst auch gerne selber den pull request erstellen

**Comment by vonMitzscha** [comment]
Aber ist die Pull Request nicht für das fertige Dokument gedacht, was, wenn es getestet wurde den Code eingefügt wird?

**Comment by Johann150** [comment]
gelöst durch #10
