### ISSUE TITLE
ISIL-Identifier

### ISSUE THREAD

**Issue by Johann150** [Handschriftenarchiv/projekt3.0#50]
Einen ISIL-Identifier bei der Staatsbibliothek Berlin beantragen.

Der Identifier muss dann in `/suche/export.php` eingetragen werden.

**Comment by vonMitzscha** [comment]
Wir gemacht

**Comment by vonMitzscha** [comment]
Beantrag und das Handschriftenarchiv ist ab sofort ein genormtes Archiv: [Sigelstelle](http://sigel.staatsbibliothek-berlin.de/suche/?isil=DE-2535) 🥂
