### ISSUE TITLE
Export Button

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#51]
Mittels `@media` Export Button in der `details.php` bei Mobilen Endgeräten nicht anzeigen.

**Comment by Johann150** [comment]
Wird das Problem nicht schon durch das ersetzen des Textes durch ein Bild gelöst?
(siehe 11109a121bdd324db156ebb7c03e13a4ed6440bc)

**Comment by vonMitzscha** [comment]
Ich weiß nicht, was du meinst. Auf eine iPad beispielsweise wird immer noch der Eport-Button angeigt, ohne, dass wenn ich ihn Drücke, etwas geschieht.

**Comment by Johann150** [comment]
Hatte vergessen, dass der weg sollte, weil er nicht funktioniert. Dachte, er soll weg, weil er designmäßig stört.
Jetzt richtig gelöst: 8ca0e42d1adbee10cc1f935f72b5182646a30dc0
