### ISSUE TITLE
Indexseiten für Verzeichnisse?

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#57]
@Johann150 gibt es eine Möglichkeit Verzeichnisse "zu verbergen" sodass man nicht folgende Ansicht bekommt?
![bildschirmfoto 2017-09-21 um 17 13 08](https://user-images.githubusercontent.com/29487728/30703558-5985db36-9ef0-11e7-8a66-d492ac48bd2b.png)

**Comment by Johann150** [comment]
Entweder einfach eine `index.php`, die woanders hin weiterleitet oder mit `.htaccess` diese Auflistungen unterbinden. Je nachdem, was dir lieber ist.

**Comment by Johann150** [comment]
Am schönsten wäre natürlich eine richtige Index-Datei.

**Comment by vonMitzscha** [comment]
Alle Unterverzeichnisse überarbeitet 😀

**Comment by Johann150** [comment]
Nein... z.B. nicht `/images/archiv`.
Es ist glaube ich doch einfacher, eine `.htaccess`-Datei zu verwenden. Ich habe mal ein Beispiel gegeben: d307d4f4b6e98c3ef30fdaa8fb8a7d5fd0bedae4

**Comment by Johann150** [comment]
Also, nach Problemen mit den anscheinen veralteten htaccess Direktive auf bplaced Servern habe ichs jetzt geschafft.
