### ISSUE TITLE
Daten übertragen

### ISSUE THREAD

**Issue by Johann150** [Handschriftenarchiv/projekt3.0#58]
Alle Daten aus der alten Datenbank in die neue Datenbank übertragen.
Die alte Datenbank als PDF unter [`/verwaltung/dokumente`](https://github.com/Handschriftenarchiv/projekt3.0/tree/master/verwaltung/dokumente) .

**Comment by Johann150** [comment]
Probleme/Fragen bis jetzt:
- Hymnus auf die Arbeit: kein Standort (in DB als Kasten 10?)
- Die Fichte: Handschrift **und** Kopie von Handschrift nicht möglich (in DB als Handschrift?) evtl. zwei Datensätze; vorl. Signatur `21-09-12` reserviert

**Comment by Johann150** [comment]
- Jan Hinnerk: siehe Die Fichte, `21-08-03` reserviert; ist im Hamburger Platt ▶️ Sprache? (erst mal `deu`)

**Comment by Johann150** [comment]
@vonMitzscha Bitte um Klärung
Das Problem wie bei _Die Fichte_ und _Jan Hinnerk_ gibt es noch sehr oft!

**Comment by vonMitzscha** [comment]
Das Problem bei KvH und H ist folgende: Der Notenschreiber damals war auch faul und hat einfach nur eine (handschriftliche) Abschrift gemacht. Und dann das ganze 30x fotokopiert. Es werden jedoch von jeder KvH mindestens 6 Exemplare behalten. Also würde ich das Problem so lösen, dass wir, wenn es das Problem gibt, dass wir Handschriften und KvH´s für einen Titel haben zwei Datenbankeinträge machen: einen für die KvH und einen für die H. Jetzt ist nur noch die Frage, ob ich auf der Wordpress-Seite gesondert angegeben haben viele von den Noten eines Titels nun Handschriften oder KvH´s sind…

**Comment by vonMitzscha** [comment]
Ich glaube das Hamburger Platt meint den Verlag und nicht die Sprache bzw. ein Heftchen in dem das ganze zu finden war 😀

**Comment by vonMitzscha** [comment]
Der Hymnus auf die Arbeit wurde aus dem Grund, dass er eventuell noch geseungen werden könnte vorerst zu dem Angegeben Standort in der NoBi überführt. Also einfach in der Signatur (wenn möglich) nichts hinschreiben oder halt die Signatur der NoBi und in der Bemerkung darauf verweisen das sich das Stück vorerst nicht im HSA befindet.

**Comment by vonMitzscha** [comment]
Zum Hamburger Platt: ich habe das im exportierten PDF nicht gefunden. Die Datei `seite 1` oder die Datei `seite 2`?

**Comment by Johann150** [comment]
Also zunächst mal: Ich würde dann einfach zwei Datensätze anlegen, ist einfacher.
Und dann ist mit Hamburger **P**latt kein Blatt gemeint, sondern Plattdeutsch. Und das stand auch vorher gar nicht dabei, sondern das habe ich nachgeschaut, weil der Titel nicht direkt nach Deutsch klang.

**Comment by vonMitzscha** [comment]
Wo hast du nachgeschaut? Im Web?

**Comment by Johann150** [comment]
<https://de.wikipedia.org/wiki/Jan_Hinnerk> (jedenfalls ist das laut dem restlichen Text im Titel dieses Lied...)

**Comment by vonMitzscha** [comment]
Ok, wir können ja Nächste Woche noch einmal im Archiv nachschauen und sonst würde ich als Normsprache `de` angeben und in den Bemerkungen auf den Dialekt verweisen…

**Comment by Johann150** [comment]
Das heißt, wir müssten auch noch mal nach den Anzahlen schauen für die betreffenden Stücke...

**Comment by vonMitzscha** [comment]
Nächste Woche Donnerstag. Am besten wir machen eine Liste mit allen Werken, die wir uns noch einmal anschauen müssen…

**Comment by Johann150** [comment]
- Wir werden säen, Weißrussen: _Veröffentlicht in_ Kasten 8 **aber** _Standort_: Kasten 9 (erst mal in Kasten 8, drum herum ist Kasten 8)

**Comment by vonMitzscha** [comment]
Achtung: Zu `Wir werden sähen, Weißrussen`: Das Veröffentlich spielt keine Rolle, da habe ich ursprünglich etwas falsch zugeorndnet. In erster Linie ist **immer** der `Standort: Kasten 9` in der anfänglichen Aufzählung!!!!!

**Comment by Johann150** [comment]
`Datenbank Seite 1.pdf` ist vollständig übernommen.

**Comment by Johann150** [comment]
und `Datenbank Seite 2.pdf` ist auch abgearbeitet.
Jetzt muss allerdings noch die Korrektheit an den realen Archivalien nachgeprüft werden.

**Comment by vonMitzscha** [comment]
**Achtung:**
Es gibt einen neue _genormte_ Weise des Erfassen von Kürzeln auf Handschriften und Kopien von Handschriften. Näheres ist im Wiki unter `Setzer` erläutert. @Johann150 ist das System auch im Rahmen deiner Vorstellungen?

**Comment by vonMitzscha** [comment]
@Johann150 
Nur so eine Frage: wäre es ein Problem, die verschiedenen Kürzel und Namen durch ein `<br>` abzutrennen, um das ganze übersichtlicher zu machen? Ich würde es auch übernehmen…

**Comment by vonMitzscha** [comment]
Kasten 1 komplett überarbeitet…

**Comment by vonMitzscha** [comment]
Kasten 2 komplett überarbeitet…

**Comment by Johann150** [comment]
In Kasten 3 jetzt bis `Gold'ne Fluren` inklusive

**Comment by Johann150** [comment]
... jetzt weiter bis inklusive `Es ging ein Sämann aus, zu säen seinen Samen`

**Comment by vonMitzscha** [comment]
Kasten 3 fertig!

**Comment by Johann150** [comment]
Kasten 4 auch (Requiem)

**Comment by Johann150** [comment]
mit 50b7bb253cc5c59e75e76bd22baf979fc2ad8c5a auch Kasten 5

**Comment by vonMitzscha** [comment]
Vorerst müssen wir aufgrund der Übernahme der Kreuzschularchives in das Stadtarchiv und damit des fehlenden Standortes die Übernahme der Daten aussetzen.
