### ISSUE TITLE
404 Seite

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#6]
Was noch praktisch wäre, wenn es eine 404 Seite (im Stil einer normalen Seite, mit dem großen Titel **404**) gäbe. Andernfalls eine Weiterleitung auf die Startseite, wenn die URL oder der Link nicht gefunden wurden…

**Comment by Johann150** [comment]
@vonMitzscha Wenn soweit OK bitte pull request mergen

**Comment by vonMitzscha** [comment]
Hab. Funktioniert aber noch nicht auf der Beta-Domain !?

**Comment by Johann150** [comment]
Schon hochgeladen? An sonsten kann es auch sein, dass der Hoster das ganze sperrt, weil glaube ich eigene 404-Seiten nur mit einem bezahlten Account möglich sind, bin aber da nicht sicher.

**Comment by vonMitzscha** [comment]
Mit WordPress hats doch auch funktioniert…

**Comment by Johann150** [comment]
Da fehlte noch die `.htaccess`-Datei, ohne die fehlt die Weiterleitung und kann natürlich nicht funktionieren.
Jetzt funktionierts.
