### ISSUE TITLE
Report a Bug

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#61]
Möglichkeit, einen Fehler auf der Website oder in der Datenbank zu melden.
Nötiges Formular in `/verwaltung/report.php`
Ideen: Auf jeder Seite befindet sich ein solcher Report-Button (wird noch eingerichtet). Drückt man einen solchen, wird man zur `/verwaltung/report.php` weitergeleitet. Dort wird automatisch schon der Ort ausgefüllt an welcher der Fehler auftritt, also von welcher Seite man gerade kommt. Anzugeben ist dann noch um welche Fehler-Kategorie es sich handelt (vgl. `/verwaltung/report.php`). Name und E-Mail-Adresse des Finders müssen nicht im Formular angeben werden. Nur der Ort, die Kategorie und eine Beschreibung des Fehlers...

**Comment by vonMitzscha** [comment]
Ich bräuchte noch Hilfe mit der E-Mail, die gesendet werden soll, wenn das Formular abgeschickt wird.

**Comment by Johann150** [comment]
Gibt's ein konkretes Problem oder so generell Hilfe?

**Comment by Johann150** [comment]
Eine Frage zum aktuellen Code: woher soll eigentlich die E-Mail-Adresse kommen? Die kann ja nirgends eingegeben werden...

**Comment by Johann150** [comment]
(Jetzt schon...)

**Comment by Johann150** [comment]
Funktioniert grundsätzlich, Kategorie wird aber noch nicht mitgeschickt.

**Comment by vonMitzscha** [comment]
@Johann150 
Könnte man eventuell über `javascript:history.back()` den Ort, wo man auf "Fehler melden" geklickt hat schon vorausfüllen?

**Comment by Johann150** [comment]
Einfacher wäre in den Link die Website, wo man herkam reinzupacken.

**Comment by Johann150** [comment]
z.B. `archiv.handschriften.bplaced.de/verwaltung/report?page=index.php`

**Comment by vonMitzscha** [comment]
Soll das jetzt schon Funktionieren?

**Comment by vonMitzscha** [comment]
Ich denke, das erstmal alles so funtkioniert…

**Comment by vonMitzscha** [comment]
Funktioniert doch noch nicht alles so, wie es soll!
Die Fehler-Kategorie wird nicht mitgeschickt. Ebenfalls der Ort. Nur die Beschreibung, die E-Mail und der Name kommen an. @Johann150 es wäre gut wenn wir das noch irgendwann bis zum 20.10 hinbekommen 😁

**Comment by Johann150** [comment]
Es fehlt immer noch die Kategorie...

**Comment by Johann150** [comment]
Fehler erkannt: die radio-Buttons sind außerhalb des `<form>`-Tags. 🤦‍♂️

**Comment by vonMitzscha** [comment]
@Johann150 
![bildschirmfoto 2017-10-11 um 19 07 45](https://user-images.githubusercontent.com/29487728/31455290-b2ca3b16-aeb7-11e7-9f59-4636efb379e9.png)

Ähm, was ist denn ein Richtiger Ort (z.B. Datenbankeintrag)?

**Comment by vonMitzscha** [comment]
Wäre es nicht Klug, den Feld `Ort` einfach als ein stinknormales Textfeld zu deklarieren?
Ich glaube kaum, dass ein Nutzer auf die Idee kommt `/verwaltung/index.php` einzugeben, zumal er ja wegen der `.htacces` nicht weiß, dass es sich um PHP handelt…

**Comment by Johann150** [comment]
Wenn du mal selber nachgeschaut hättest, dann wüsstest du, dass die überhaupt nicht überprüft wird, sondern einfach nur festgestellt wird, ob überhaupt was drin steht.

**Comment by vonMitzscha** [comment]
Funtkioniert alles 😄
