### ISSUE TITLE
Issuu Embeded

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#63]
Entweder issuu will das nicht, oder ich habe etwas übersehen: wie kann man die Breite des issuu-Iframes in der `suche/details.php` auf `width: 50%;` ändern?

**Comment by Johann150** [comment]
Du musst den `<iframe>` erst aus der Tabelle nehmen, an sonsten wird das auf die Hälfte der Tabellen-Zelle gesetzt.

**Comment by vonMitzscha** [comment]
Das ist nicht das Problem. In der Tabelle liegt nur der Code. Das Problem muss irgendwie bei issuu liegen:

**Comment by vonMitzscha** [comment]
Mir ist gerade aufgefallen, dass man alle Einstellungen (wie Color, width,…) auf der Issuu-Embedded Seite macht und diese Einstellungen dann mit einen eindeutigen und einmaligen Link verbunden werden. So kann man beispielsweise die Hintergrundfarbe beeinflussen. Aber du kannst ja mal die `details.php`´s von `id1` und `id134` vergleichen. Irgendwie sehen die Player schon anders aus (abgesehen davon, dass es irgendwie zwei verschiedene Formate sind).

**Comment by vonMitzscha** [comment]
Button (wie bei Export) statt Digitalisierung mit Link zur Issuu Resource. Link in die Datenbank einfügbar machen…

**Comment by vonMitzscha** [comment]
Neuer Branch für Digitalisierungen in der `details.php` !

**Comment by vonMitzscha** [comment]
Fehler lokalisiert, weiß aber nicht, wie er behoben werden soll: Wenn in der Datenbank zu dem Werk Bermerkungen in der zugehörigen Spalte eingetragen werden, dann ist immer die erste Digitalisierung im "hässlichen" Layout. Die darauffolgenden sind dann so, wie im Quellcode angegeben. 
Exisitert zu einem Werk keine Bemerkung (was bald nicht mehr der Fall sein wird #58 ) so wird gleich die erste Digitalsierung im richtigen Layout angezeigt…
![bildschirmfoto 2017-10-08 um 13 15 15](https://user-images.githubusercontent.com/29487728/31316312-20328b48-ac2b-11e7-9423-759862a2cda9.png)

**Comment by vonMitzscha** [comment]
@Johann150 Lösungsansatz? 😄

**Comment by vonMitzscha** [comment]
Embedded Breite muss 50% betragen...

**Comment by vonMitzscha** [comment]
Gäbe es eine möglichkei die `<div id="branding">` vor dem Anzeigen im Broswer zu unterbinden?

**Comment by Johann150** [comment]
Theoretisch ist das mit JavaScript möglich, **aber** da der `<iframe>` etwas von einer anderen Webseite enthält, ist sein Inhalt *cross-origin*, wodurch man mit JS nicht auf den Inhalt des `<iframe>`'s zugreifen kann.
Also leider **nicht**.

**Comment by vonMitzscha** [comment]
Ok. Nicht ohne Grund soll man ja auch auf Issuu-Pro upgraden…

**Comment by vonMitzscha** [comment]
Neue Idee: da die Embeddes immer noch so sind, wie sie sein wollen:
Was wäre, wenn man eine Galerie (wie in`index.php#werk`) macht, in der einfach ein Vorschaubild der Digitalisierung ist und wenn man drauf Klickt, man gleich zu issuu.com weitergeleitet wird?
Wäre das mit der Datenbank realisierbar oder müsste ich das dann manuell machen?

Ich stelle mir das Gar Nicht so schlecht vor und man würde damit hässliche, nicht responsible Embbededs vorbeugen und auch auf den ersten Blick, dass sich um einen externen Dienst handelt…

**Comment by Johann150** [comment]
Meinst du damit, wir sollten einfach das Vorschaubild *gleich von Issuu* nehmen und das dann einfach als Link verwenden?

**Comment by vonMitzscha** [comment]
Genau!
…und Bestenfalls als Link die Galerie als "Vorlage" bzw. Grundkonstrukt verwenden.
Wäre so etwas möglich?

**Comment by Johann150** [comment]
Also die vorschaubilder bekommt man mit (z.B.) `<img src="https://image.isu.pub/170325114428-708a398fd362e30d43eab3d28211e2e3/jpg/page_1.jpg"/>`

**Comment by Johann150** [comment]
Die Frage ist nur, ob man das irgendwie rausbekommt. Gibts da irgendeine Verbindung mit diesem Kauderwelsch (`image.isu.pub/`**`170325114428-708a398fd362e30d43eab3d28211e2e3`**`/jpg...`)?

**Comment by vonMitzscha** [comment]
Ich glaube das ist immer extra fürs Bild bzw. Digitalisat
Vielleicht findet man ja hier etwas…
[https://developers.issuu.com](https://developers.issuu.com)

**Comment by Johann150** [comment]
mit https://issuu.com/oembed?url=https://issuu.com/hsa6/docs/mein_freund__ich_tu_dir_nicht_unrec_d31900bc7972b5&format=json könnte man das Thumbnail per Javascript bekommen. Dazu müssten wir allerdings die komplette URL eines Digitalisats irgendwie abspeichern.

**Comment by Johann150** [comment]
Allerdings wäre es einfacher, weil man nicht jedes mal ein Embed auf issuu erstellen müsste. Es müssten dann aber auch die schon eingetragenen Digitalisate entfernt und mit der richtigen URL neu eintragen werden.

**Comment by Johann150** [comment]
mit #100 abgeschlossen
