### ISSUE TITLE
Graphs

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#64]
Graph wird in der `http://archiv.handschriften.bplaced.de/verwaltung/graphs?archivalien` nicht angezeigt…

**Comment by Johann150** [comment]
Wahrscheinlich ein Fehler mit der SQL-Abfrage

**Comment by vonMitzscha** [comment]
?
![bildschirmfoto 2017-10-01 um 15 19 09](https://user-images.githubusercontent.com/29487728/31054872-ea1baf54-a6bb-11e7-96ec-0bcd815fb6cf.png)

**Comment by Johann150** [comment]
`graphs.php?archivalien` funktioniert immer noch nicht.

**Comment by Johann150** [comment]
Das Problem sind Anführungszeichen in einem der Titel, was JavaScript nicht gefällt.

**Comment by vonMitzscha** [comment]
Die wollten wir ja sowieso im Rahmen der Datenbanküberarbeitng entfernen: ich werde das mal schnell managen…

**Comment by Johann150** [comment]
Nein, passt schon!
