### ISSUE TITLE
Autoren im Blog hinzufügen

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#66]
Das Anzeigen des Autor, dessen Beschreibung, und Abstracts des Blogeintrages am Ende anzeigen.[Beispiel am Ende…](https://protonmail.com/blog/prevent-email-hacking/)

**Es darf jedoch nicht der Counter genutzt werden!**

**Comment by vonMitzscha** [comment]
`<br><br><a href="."><p>Zurück zur Eintrags-Übersicht</p></a>` ebenfalls in dieser "Box" mitanzeigen…

**Comment by vonMitzscha** [comment]
Jetzt zu allen Blogeinträge das Feature hinzugefügt, dass man Autoren, Redakteure und Veröffentlicher hinzufügen kann.
Es gibt zwei Typen, den Autor anzugeben:
1.) Der Autor sowie der Redakteur sind interne Mitarbeiter --> Div **mit** Avatar
2.) Einer der aufgeführten Personen ist kein internes, entwickelndes Mitglied des HSA --> einfache Tabelle…

**Comment by vonMitzscha** [comment]
@Johann150 Hast du zufällig eine Idee, wie man die Buttons am Ende eines jeden Blogeintrages responsive machen könne. Jetzt ist es noch nicht so optimal 😁

**Comment by Johann150** [comment]
mit 14885cb010b2352fbfb32179b4d3b9d7821627d4 und `display: flex` sind die Buttons jetzt zufriedenstellend, oder?

**Comment by vonMitzscha** [comment]
Flex überall ergänzen, dann ist es geschafft…

**Comment by Johann150** [comment]
Wurde ja jetzt durch die vereinfachte Blog-Übersetzung vorweggenommen.
