### ISSUE TITLE
RSS-Feed für Blog

### ISSUE THREAD

**Issue by Johann150** [Handschriftenarchiv/projekt3.0#67]
einen RSS-Feed für Blog-Updates anlegen, damit die Nutzer wissen, wenn es was neues gibt.
@vonMitzscha Denkst du, dass das angebracht ist? Oder gibt es sowieso immer eine Nachricht über Twitter?

**Comment by vonMitzscha** [comment]
Ich denke, dass wird nicht notwendig sein, da ich **immer** über Twitter Nachrichten zu Neuigkeiten (wie dem Blog) bringen werde…
