### ISSUE TITLE
Datenfeature: Digitalisierung erlaubt

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#70]
Die Möglichkeit, in der Datenbank zu signalisieren, ob ein Werk digitalisiert werden darf oder nicht. Ein Werk darf erst 70 Jahre nach dem Tod des Komponisten digitalisiert werden, da der Komponist als der Urheber des Werkes gilt (und nicht der Schreiber, der das Werk des Komponisten auch nur "Abgeschrieben hat")

**Comment by Johann150** [comment]
Wird man wohl manuell machen müssen.  
Also einfach ein neues Feld in der Datenbank.

**Comment by vonMitzscha** [comment]
Genau. In das kann man dann einfach j und n, oder was weiß ich eintragen…

**Comment by Johann150** [comment]
Irgendwelche Namensvorschläge/-wünsche?

**Comment by jugendhacker** [comment]
Ihr könntet auch einfach einen Boolean bzw. Bit Wert nehmen

**Comment by Johann150** [comment]
Das ist aber kein Namensvorschlag 😉 .
Das ist klar, es muss halt nur mal jemand in die Datenbank einfügen. Und dafür braucht man nun mal einen Namen für die Tabellen-Spalte.

**Comment by vonMitzscha** [comment]
Wie wäre es mit `law` wg. Archivgesetzt…

**Comment by Johann150** [comment]
Wieso auf Englisch, wenn die restliche Datenbank auf Deutsch ist?

**Comment by Johann150** [comment]
Ich bin für `LegalDigital` oder `DigitalLegal`

**Comment by Johann150** [comment]
@vonMitzscha so i.O.?
