### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by jugendhacker** [Handschriftenarchiv/projekt3.0#71]
Ihr veröffentlicht hier eine Arbeit ohne eine dazugehörige Lizenz als "Open Source", dies macht es aber für andere unmöglich bei der Entwicklung zu helfen ohne gegen euer Copyright zu verstoßen!

**Comment by vonMitzscha** [comment]
Lizenz wurde angelegt:
[Lizenz](https://github.com/Handschriftenarchiv/projekt3.0/blob/master/LICENSE)

**Comment by jugendhacker** [comment]
Jetzt darf man euch endlich legal helfen beim coden!
