### ISSUE TITLE
config.php

### ISSUE THREAD

**Issue by jugendhacker** [Handschriftenarchiv/projekt3.0#73]
Könntet ihr bitte mal eine Art Sample hochladen + einen Datenbank Dump der alle Tabellen ohne Inhalt enthält damit ich das auf meinem Lokalen Server ordentlich ausführen kann?

**Comment by Johann150** [comment]
siehe `/archivalien.sql`

**Comment by Johann150** [comment]
config.php wäre dann wie folgt:
```PHP
<?php

function dbCon(){
	$con=mysqli_connect("<Host>","<Benutzername>","<Passwort>","<Datenbank-Name>");
	mysqli_set_charset($con,'utf8');
	return $con;
}
```

**Comment by jugendhacker** [comment]
Danke
