### ISSUE TITLE
Tabellenrahmen?

### ISSUE THREAD

**Issue by Johann150** [Handschriftenarchiv/projekt3.0#8]
Wie wäre es mit einem Rahmen zwischen den Zellen der Tabelle bei `details.php`, wie im Bild:

![grafik](https://user-images.githubusercontent.com/20990607/28179292-c84791ca-6801-11e7-87cd-57d8b9f7768f.png)

**Comment by vonMitzscha** [comment]
Um Himmelswillen Nein.
Frei stehende Angaben sehen viel besser aus. nicht wie Web 1.0…
