### ISSUE TITLE
Links berichtigen

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#84]
Die Links funktionieren nicht alle, so wie sie sollen…

**Comment by vonMitzscha** [comment]
z.B. Blog, Verwaltung

**Comment by Johann150** [comment]
Das im Blog scheint ein Fehler in der Safari Preview zu sein. Bei mir und auch in der stable Version von Safari funktionierts.

**Comment by Johann150** [comment]
Wir sollten aber trotzdem mal **alle Links überprüfen.**
Unter anderem sollten wir auch darauf achten, dass Resourcen wie Bilder, CSS, JavaScript usw. mit absoluten URLs eingebunden werden.
Bei Links sollte es dann aber wieder keine absoluten URLs geben, sondern relative, damit das `/de/` usw. erhalten bleibt.

**Comment by Johann150** [comment]
Das Problem scheint doch nicht mit der Safari Preview zusammenhängen; bei mir ist es auch gerade passiert. Die Ursache liegt (mehr oder weniger) in der `.htaccess` bzw. ist es hier zu lösen.

Das Problem ist, dass ich z.B. auf `/blog` gehe, also **ohne Slash**. `/blog` ist ja ein Verzeichnis und ich bekomme die `/blog/index.php` angezeigt. Aber der Browser *weiß das ja nicht* und denkt somit, ich schaue eine Datei an und wenn ich auf einen Link klicke, dann bleibe ich im aktuellen Verzeichnis, also `/` (blog ist ja scheinbar nur eine Datei in diesem Verzeichnis).

Wenn ich jetzt stattdessen auf `/blog/`, also **mit Slash**, gehe, dann funktioniert alles einwandfrei, weil der Browser hier eindeutig sieht, dass ich in einem Verzeichnis bin.

**Comment by Johann150** [comment]
Man müsste also, wenn es sich um ein Verzeichnis handelt, ein Slash an die URL anhängen und dann den Browser an die so entstandene URL weiterleiten, damit er kapiert, dass es ein Verzeichnis ist.

**Comment by Johann150** [comment]
Ups, jetzt gibts wieder eine Weiterleitung von `/de/blog` auf `/blog/?lang=de`, was gerade nicht gewollt war.

**Comment by Johann150** [comment]
Evtl. könnte man auch noch den Footer so überarbeiteiten.

**Comment by Johann150** [comment]
Mir ist heute auch noch bei der Übersetzung des Blogs aufgefallen: Die Links in den Übersetzungen sollten auch noch mal alle überprüft werden.
Die Links in den ganzen Blog-Übersetzungen habe ich jetzt schon im `blog-translate`-Branch korrigiert.

**Comment by Johann150** [comment]
weiterer Fehler: Bei dem `Handschriftenarchiv`-Schriftzug, der sich auf allen Seiten oben links befindet, sollte das `href`-Attribut noch geändert werden.
```PHP
<a href="/<?php echo $use_lang; ?>/">Handschriftenarchiv</a>
```
