### ISSUE TITLE
einheitliche Gestaltung der Blogeinträge

### ISSUE THREAD

**Issue by Johann150** [Handschriftenarchiv/projekt3.0#90]
Im Rahmen der Umgestaltung des Blogs wäre es schön, wenn alle Blogeinträge einen einheitlichen Hintergrund bekommen könnten. Danach würde sich dann die Hintergrund-Farbe der Navigations-Leiste richten.

**Comment by vonMitzscha** [comment]
Ich mache mich an die Arbeit…

**Comment by Johann150** [comment]
Meine Idee wäre folgende:

Es müssten folgende Seiten noch einen weißen Hintergrund erhalten:
- [ ] netzneutralität
- [ ] tools-1

Es muss ja nicht die ganze Webseite einen weißen Hintergrund bekommen; es reicht aus, wenn der letzte Abschnitt einen weißen Hintergrund bekommt.

**Comment by vonMitzscha** [comment]
Jeschaffd
