### ISSUE TITLE
Master funktionstüchtig machen!

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#93]
Es kann nicht sein, dass der Master nicht funktioniert. Wir brauchen wenigstens **eine** Basis, die man im Falle einer Überschreibung auf der Domain hochladen kann!

**Comment by vonMitzscha** [comment]
um `index.php` zum funktionieren zu bringen auf uralt Datei zurück gegriffen (`Index.funktionstüchtig.php`)

**Comment by vonMitzscha** [comment]
Impressum.php ersetzt durch `Impressum.funtkionstüchtig.php`, da irgendetwas mit dem Style im Master falschläuft!!

**Comment by Johann150** [comment]
Mögliche Fehlerquellen:
* Wann hast du das letzte mal hochgeladen gehabt? (Ich hab nicht mehr auf die offfizielle Webseite hochgeladen).
* Seitdem haben wir die Pfade zu den ganzen Stylesheets, Bildern und JavaScript-Dateien geändert.

**Comment by vonMitzscha** [comment]
Ich hab heute Testweise auf die Domain archiv.hsa3.bplaced.de den ganzen Master hochegeladen, um zu prüfen, ob ich auf diese Weise auch bei archiv.handschriften.bplaced.de weiterarbeiten kann. Und es hat nicht funktioniert
Zum Teil wegen der Pfade (vielleicht sollten wir mal einen Pullrequest machen, wenn wir über all schon einmal die Pfade geändert haben) und zum anderen teil hat er Wegen der Translation Sachen rumgesetzt und in der Datenbank wurde die Seite, sobald du etwas eingeben wolltest weiß…

**Comment by vonMitzscha** [comment]
Also wir müssen einfach archiv.hsa3.bplaced.de zum laufen bringen, dann funktioniert der Master auch wieder…
und in Zukunft müssen wir einfach mit ein paar Branches arbeiten

**Comment by Johann150** [comment]
Jetzt siehts erst mal gut aus.
