### ISSUE TITLE
Datenbank Fehler!

### ISSUE THREAD

**Issue by vonMitzscha** [Handschriftenarchiv/projekt3.0#96]
Es gibt noch einen, mir nicht erklärbaren Fehler, der sowohl in Safari als auch in Firefox auftritt: Wenn man in der Datenbank einen begriff suchen will kann es *manchmal* passieren, dass sich in Safari ein Weißes Element mit Menü (was aber nicht funktioniert))vor alles schiebt oder in Firefox alles unnatürlich herangezoomt wird. Tritt dieser Fall ein, kann man zwar ganz normal seinen Begriff suchen und Enter drücken, wird aber, egal, was man eingegeben hat, auf die 404-seite weitergeleitet…
Alles auch noch einmal im Video… (leider nur als Link, da die Datei nicht von Github anerkannt wurde)
[https://we.tl/1YRmikzwPd](https://we.tl/1YRmikzwPd)

**Comment by Johann150** [comment]
Eigentlich kann das gar nicht sein, denn in `/suche/index.php` gibt es gar kein Menü. 😕

**Comment by Johann150** [comment]
Bei mir (Firefox) ist das ganze auch nicht reproduzierbar.

**Comment by vonMitzscha** [comment]
Komisch. Ich habe keine Ahnung, aber vielleicht was mit der `.htaccess` ? 
ich kann ja noch einmal das ganze bei mir machen und das Problem mit der Konsole untersuchen…

**Comment by vonMitzscha** [comment]
Komisch: momentan kann ich das ganze auch nich wiederholen…
Jetzt funktioniert wieder alles Wunderbar…
Ich würde dieses Issue aber trotzdem noch nicht löschen. Vielleicht passiert das ganze ja noch mal, und dann kann ich der Website mit der Konsole zu Leibe rücken…

**Comment by Johann150** [comment]
Also ist noch mal festzuhalten: Beim hochladen passiert irgendwas mysterisches, was die Webseite zerhaut...

**Comment by vonMitzscha** [comment]
Ich habe festgestellt, dass dieser Fehler der Weißen Seite Über dem Suchformular nur in den Beta-versionen der Browser Safari [Prewview Technology] und Firefox [Nightly] auftritt. D.h. unter dem Aspekt, dass es in den normalen Browser erst einmal funktioniert können wir diesen Bug ein bisschen vernachlässigen…

**Comment by vonMitzscha** [comment]
Das Problem ist, dass diese misteriöse Seite auch die **normalen** mobile Browser auf iOS betreffen (Safari, Firefox). Ich werden den Code noch einmal durchforsten, warum auf der `suche/index.php` dieser Fehler zustande kommen könnte…
Leider ist durch diesen Fehler das mobile Suchen unmölglich geworden. Trotzdem würde ich sagen, dass #99 zu 100% Vorrang hat.

**Comment by vonMitzscha** [comment]
Update: aus dem Grund heraus, dass jeder Browser betroffen ist, hat dieses Issue doch schon eine gewisse Priorität…!

**Comment by vonMitzscha** [comment]
Ich habe eine mögliche Ursache Entdeckt: wenn man Beginnt, etwas in die Suche einzigen wird aus der URL `http://archiv.handschriften.bplaced.de/de/suche` zu `http://archiv.handschriften.bplaced.de/de/suche#`. Und das # ist ja auch der Aufruft für das Menü, oder? Zumindest, die Frage: woher kommt das **#**?

**Comment by Johann150** [comment]
Also es war mal wieder ein gewisser Umleitungsfehler. von `/de/suche` zu `/de/suche/`.
Deshalb konnte das Javascript, das im Hintergrund arbeitet seine Daten nicht richtig bekommen und hat die ganze Seite kaputt gemacht.

**Comment by Johann150** [comment]
Nach dem Reparieren gilt dann allerdings auch noch mal hier #84 !
Denn die `search.php` ist noch nicht berichtigt. @vonMitzscha könntest du das bitte noch machen?
